name: Get Regions
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  GetRegions:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: |
          curl cip.cc
          cat /etc/apt/sources.list
          sudo apt tree 
          tree ${{ github.workspace }}
      - name: Publish reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jfoa-build-reports-${{ runner.os }}
          path: runner/build/reports/